import { LucideIcon } from 'lucide-react';
import {
  CloudRain,
  Timer,
  Rocket,
  Bomb,
  Shield,
  Footprints,
  Skull,
  Brain,
  RefreshCw,
  Link2,
  Swords,
  Scale,
  ArrowUpDown,
  Target,
  LayoutGrid,
  Search,
  Compass,
} from 'lucide-react';

export type GameCategory = 'All' | 'Speed' | 'Survival' | 'Memory' | 'Battles' | 'Challenges';

export interface GameCatalogItem {
  id: string;
  title: string;
  category: 'Speed' | 'Survival' | 'Memory' | 'Battles' | 'Challenges';
  description: string;
  badge: string;
  difficultyBadge: 'Beginner' | 'Normal' | 'Hard' | 'Expert';
  icon: LucideIcon;
  colorClass: string;
  bgClass: string;
  borderClass: string;
}

export const GAME_CATALOG: GameCatalogItem[] = [
  // Speed (4)
  {
    id: 'rain_calculation',
    title: 'Rain Calculation',
    category: 'Speed',
    description: 'Pop falling arithmetic raindrops before they hit the splash zone.',
    badge: 'Falling Drops',
    difficultyBadge: 'Normal',
    icon: CloudRain,
    colorClass: 'text-cyan-400',
    bgClass: 'from-cyan-950/40 to-slate-900',
    borderClass: 'border-cyan-500/30 hover:border-cyan-400',
  },
  {
    id: 'rush_60',
    title: '60-Second Rush',
    category: 'Speed',
    description: 'Global 60-second time attack with sub-second bonuses and combo streak extensions.',
    badge: 'Time Attack',
    difficultyBadge: 'Normal',
    icon: Timer,
    colorClass: 'text-amber-400',
    bgClass: 'from-amber-950/40 to-slate-900',
    borderClass: 'border-amber-500/30 hover:border-amber-400',
  },
  {
    id: 'rocket_launch',
    title: 'Rocket Math',
    category: 'Speed',
    description: 'Propel your rocket through atmospheric stages into orbit against constant gravity.',
    badge: 'Altitude Rush',
    difficultyBadge: 'Hard',
    icon: Rocket,
    colorClass: 'text-indigo-400',
    bgClass: 'from-indigo-950/40 to-slate-900',
    borderClass: 'border-indigo-500/30 hover:border-indigo-400',
  },
  {
    id: 'bomb_defusal',
    title: 'Bomb Defusal',
    category: 'Speed',
    description: 'Cut colored wires before their ticking fuses detonate. Mistakes burn fuses 2x faster.',
    badge: 'Ticking Fuse',
    difficultyBadge: 'Expert',
    icon: Bomb,
    colorClass: 'text-red-400',
    bgClass: 'from-red-950/40 to-slate-900',
    borderClass: 'border-red-500/30 hover:border-red-400',
  },

  // Survival (3)
  {
    id: 'survival_endurance',
    title: 'Survival Endurance',
    category: 'Survival',
    description: 'Classic 3-lives endurance through escalating waves. Shields & heart recovery on streaks.',
    badge: 'Endurance',
    difficultyBadge: 'Normal',
    icon: Shield,
    colorClass: 'text-red-400',
    bgClass: 'from-rose-950/40 to-slate-900',
    borderClass: 'border-rose-500/30 hover:border-rose-400',
  },
  {
    id: 'calculation_runner',
    title: 'Calculation Runner',
    category: 'Survival',
    description: '3-lane perspective runner. Steer into the lane carrying the correct answer before impact.',
    badge: '3-Lane Action',
    difficultyBadge: 'Hard',
    icon: Footprints,
    colorClass: 'text-cyan-400',
    bgClass: 'from-teal-950/40 to-slate-900',
    borderClass: 'border-teal-500/30 hover:border-teal-400',
  },
  {
    id: 'boss_battle',
    title: 'Boss Battle Arena',
    category: 'Survival',
    description: 'Active Time Battle RPG against legendary math bosses with charge meters and combos.',
    badge: 'RPG Arena',
    difficultyBadge: 'Expert',
    icon: Skull,
    colorClass: 'text-purple-400',
    bgClass: 'from-purple-950/40 to-slate-900',
    borderClass: 'border-purple-500/30 hover:border-purple-400',
  },

  // Memory (3)
  {
    id: 'memory_calculation',
    title: 'Memory Calculation',
    category: 'Memory',
    description: 'Card flashes for 1.8 seconds and flips face-down. Solve strictly from mental memory.',
    badge: 'Flash Memory',
    difficultyBadge: 'Normal',
    icon: Brain,
    colorClass: 'text-indigo-400',
    bgClass: 'from-indigo-950/40 to-slate-900',
    borderClass: 'border-indigo-500/30 hover:border-indigo-400',
  },
  {
    id: 'operation_switch',
    title: 'Operation Switch',
    category: 'Memory',
    description: 'Cognitive flexibility test. Operators dynamically switch between +, −, ×, and ÷.',
    badge: 'Agility',
    difficultyBadge: 'Hard',
    icon: RefreshCw,
    colorClass: 'text-emerald-400',
    bgClass: 'from-emerald-950/40 to-slate-900',
    borderClass: 'border-emerald-500/30 hover:border-emerald-400',
  },
  {
    id: 'table_chain',
    title: 'Table Chain',
    category: 'Memory',
    description: 'Sequence pattern deduction. Determine the times-table interval to fill missing sequence slots.',
    badge: 'Sequence',
    difficultyBadge: 'Normal',
    icon: Link2,
    colorClass: 'text-amber-400',
    bgClass: 'from-amber-950/40 to-slate-900',
    borderClass: 'border-amber-500/30 hover:border-amber-400',
  },

  // Battles (3)
  {
    id: 'table_battle',
    title: 'Table Battle',
    category: 'Battles',
    description: 'Head-to-head multiplication tables duel. Decide whether left is <, =, or > right.',
    badge: 'Duel',
    difficultyBadge: 'Normal',
    icon: Swords,
    colorClass: 'text-amber-400',
    bgClass: 'from-amber-950/40 to-slate-900',
    borderClass: 'border-amber-500/30 hover:border-amber-400',
  },
  {
    id: 'quick_compare',
    title: 'Quick Compare',
    category: 'Battles',
    description: 'Compare arithmetic expressions across operations with rapid-fire <, =, and > decisions.',
    badge: 'Comparison',
    difficultyBadge: 'Normal',
    icon: Scale,
    colorClass: 'text-blue-400',
    bgClass: 'from-blue-950/40 to-slate-900',
    borderClass: 'border-blue-500/30 hover:border-blue-400',
  },
  {
    id: 'bigger_smaller',
    title: 'Bigger or Smaller',
    category: 'Battles',
    description: 'Evaluate whether a dynamic arithmetic problem is greater or less than a benchmark threshold.',
    badge: 'Threshold',
    difficultyBadge: 'Normal',
    icon: ArrowUpDown,
    colorClass: 'text-teal-400',
    bgClass: 'from-teal-950/40 to-slate-900',
    borderClass: 'border-teal-500/30 hover:border-teal-400',
  },

  // Challenges (4)
  {
    id: 'number_target',
    title: 'Number Target',
    category: 'Challenges',
    description: 'Combine given number tiles and operations to build an expression matching the target value.',
    badge: 'Tile Puzzle',
    difficultyBadge: 'Hard',
    icon: Target,
    colorClass: 'text-indigo-400',
    bgClass: 'from-indigo-950/40 to-slate-900',
    borderClass: 'border-indigo-500/30 hover:border-indigo-400',
  },
  {
    id: 'table_breaker',
    title: 'Table Breaker',
    category: 'Challenges',
    description: 'Breakout brick wall demolition. Solve calculations to shatter each colored brick.',
    badge: 'Demolition',
    difficultyBadge: 'Normal',
    icon: LayoutGrid,
    colorClass: 'text-amber-400',
    bgClass: 'from-amber-950/40 to-slate-900',
    borderClass: 'border-amber-500/30 hover:border-amber-400',
  },
  {
    id: 'find_mistake',
    title: 'Find the Mistake',
    category: 'Challenges',
    description: 'Audit 4 displayed arithmetic equations and immediately spot the single erroneous calculation.',
    badge: 'Error Audit',
    difficultyBadge: 'Normal',
    icon: Search,
    colorClass: 'text-rose-400',
    bgClass: 'from-rose-950/40 to-slate-900',
    borderClass: 'border-rose-500/30 hover:border-rose-400',
  },
  {
    id: 'closest_answer',
    title: 'Closest Answer',
    category: 'Challenges',
    description: 'Mental rounding and magnitude estimation. Pick the closest estimate without scratch paper.',
    badge: 'Estimation',
    difficultyBadge: 'Expert',
    icon: Compass,
    colorClass: 'text-cyan-400',
    bgClass: 'from-cyan-950/40 to-slate-900',
    borderClass: 'border-cyan-500/30 hover:border-cyan-400',
  },
];
